apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    app: mongo-db
  namespace: product-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      hostname: mongo-db
      containers:
        - image: mongo:3.6.9
          name: mongo-db
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
          - name: mongodbport
            containerPort: 27017
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
  namespace: product-services
spec:
  type: NodePort
  selector:
    app: mongo-db
  ports:
    - targetPort: 27017
      port: 27017
#      nodePort: 30017
