apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deploy
  labels:
    app: recommendation-deploy
  namespace: product-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - image: 122443366744.dkr.ecr.ap-northeast-2.amazonaws.com/cdk-hnb659fds-container-assets-122443366744-ap-northeast-2:recommendation-service-0.0.2
        imagePullPolicy: Always
        name: recommendation-service
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
  namespace: product-services
spec:
  type: NodePort
  selector:
    app: recommendation-service
  ports:
    - targetPort: 8080
      port: 8080
